### PR TITLE
Convert Vue components to class-style

### PR DESCRIPTION
**Pull request by mdempsky**
The diff looks large, but it's mostly mechanical: instead of

    export default {
      data() {
        return {
          x: 42,
          y: "quux",
        };
      },
      created() { ... },
      methods: {
        foo() { ... },
        bar() { ... },
      },
    };

we can now write components as (almost) normal TypeScript classes:

    @Component
    export default class MyComponent extends Vue {
      x = 42;
      y = "quux";

      created() { ... }
      foo() { ... }
      bar() { ... }
    }

There are a couple minor gotchas to be aware of, but they're reasonably documented:

https://vuejs.org/v2/guide/typescript.html#Class-Style-Vue-Components
https://github.com/vuejs/vue-class-component

### CODE REVIEW

**Comment by mdempsky** [comment]
If you want to review the changes, I suggest using `git diff`'s `--ignore-space-change` flag.

Otherwise, just take a look at how the code looks now, and let me know if you think the class style is an improvement over what we had before.

**Comment by jakehobbs** [comment]
Sorry, somehow I missed this. I'm fine with it if the conflicts are resolved.

**Comment by jakehobbs** [comment]
@mdempsky do we want to revisit this?

**Comment by mdempsky** [comment]
Probably, but I'm going to close for now. I'll reopen once I have time to look at it again. It's not urgent.

**Pull request closed without merging**
